name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build go-slang
        run: |
          cd go-slang
          npm ci
          npm run build
          npm test
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm link ../go-slang
          npm run build-gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
